accounts/urls.py
from django.urls import path, include
from . import views

app_name="accounts"

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
]

board/urls.py
from django.urls import path, include
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.index, name="index"),
    path('create', views.create, name="create"),
    path('<int:id>/like/', views.like, name="like"),
    path('<int:id>/comment_create', views.comment_create, name="comment_create"),
    path('<int:id>/update', views.update, name="update"),
    path('<int:id>/comment_delete', views.comment_delete, name="comment_delete"),
]

quest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('board/', include('board.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

board/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Board(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    user_likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_users")
    
    
class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)

board/forms.py
from django import forms
from .models import Board, Comment

class BoardForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ('content',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
# Create your views here.
# def login(request):
#     return

def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('board:index')
    else:
        form = UserCreationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/form.html', context)


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('board:index')
    else:
        form = AuthenticationForm(request)
    context = {
        'form': form
    }
    return render(request, 'accounts/form.html', context)

def logout(request):
    auth_logout(request)
    return redirect('board:index')

board/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Board, Comment
from .forms import BoardForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST

# Create your views here.
def index(request):
    boards = Board.objects.all()
    form = CommentForm()
    context = {
        'boards': boards,
        'form': form,
    }
    return render(request, 'board/index.html', context)


def create(request):
    if request.method == "POST":
        form = BoardForm(request.POST)
        if form.is_valid():
            board = form.save(commit=False)
            board.user = request.user
            board.save()
            return redirect('board:index')
    else:
        form = BoardForm()
    context = {
        'form':form
    }
    return render(request, 'board/form.html', context)

@login_required
def like(request, id):
    board = get_object_or_404(Board, id=id)
    user = request.user
    if user in board.user_likes.all():
        board.user_likes.remove(user)
    else:
        board.user_likes.add(user)
    return redirect('board:index')


def comment_create(request, id):
    board = get_object_or_404(Board, id=id)
    user = request.user
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = user
            comment.board = board
            comment.save()
    return redirect("board:index")


@require_POST
def comment_delete(request, id):
    comment = get_object_or_404(Comment, id=id)
    comment.delete()
    return redirect("board:index")


def update(request, id):
    board = get_object_or_404(Board, id=id)
    if request.method == "POST":
        form = BoardForm(request.POST, instance=board)
        if form.is_valid():
            board = form.save(commit = False)
            board.user = request.user
            board.save()
            return redirect('board:index')
    else:
        form = BoardForm(instance=board)
    context = {
        'form': form
    }
    return render(request, "board:form", context)

accounts/templates/accounts/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit">
  </form>
{% endblock %}

board/templates/board/form.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block body %}
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit">
  </form>
{% endblock %}

board/templates/board/index.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
  <h1>Index</h1>
  <p>{{user}}</p>
  <a href="{% url 'accounts:signup' %}">SignUp</a>
  <a href="{% url 'accounts:login' %}">Login</a>
  <a href="{% url 'accounts:logout' %}">Logout</a>
  <a href="{% url 'board:create' %}">Write</a>
  {% for board in boards %}
    <p>{{board.user}}</p>
    <p>{{board.content}}</p>
    <p>{{board.user_likes.all.count}}</p>
    <a href="{% url 'board:like' board.id %}">Like</a>
    <form action="{% url 'board:comment_create' board.id %}" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit">
    </form>
    {% for comment in board.comment_set.all %}
      <span>{{comment.user}}</span> <p></p> <span>{{comment.content}}</span>
      <form action="{% url 'board:comment_delete' comment.id %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="댓글삭제">
      </form>
    {% endfor %}
    <hr>
  {% endfor %}
{% endblock %}

quest/templates/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  {% bootstrap_css %}
</head>
<body>
  {% block body %}
  {% endblock %}
  {% bootstrap_javascript jquery='full' %}
</body>
</html>